name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Heroku CLI
      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # Log in to Heroku Container Registry
      - name: Log in to Heroku Container Registry
        run: |
          echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

      # Set Heroku stack to container
      - name: Set Heroku stack to container
        run: |
          heroku stack:set container --app $HEROKU_APP_NAME

      # Set environment variables in Heroku
      - name: Set Heroku environment variables
        run: |
          heroku config:set VITE_PHD_CERTIFICATE_URL=$VITE_PHD_CERTIFICATE_URL \
                           VITE_PHD_JURY_REPORT_URL=$VITE_PHD_JURY_REPORT_URL \
                           VITE_ENG_CERTIFICATE_URL=$VITE_ENG_CERTIFICATE_URL \
                           VITE_HK_HOST_1=$VITE_HK_HOST_1 \
                           VITE_HK_HOST_2=$VITE_HK_HOST_2 \
                           VITE_HK_HOST_3=$VITE_HK_HOST_3 \
                           VITE_PORT=$VITE_PORT \
                           --app $HEROKU_APP_NAME

      # Build and push the Docker image to Heroku
      - name: Build and push Docker image
        run: |
          docker build --build-arg VITE_PORT=$VITE_PORT  \
                       --build-arg VITE_HK_HOST_1=$VITE_HK_HOST_1  \
                       --build-arg VITE_HK_HOST_2=$VITE_HK_HOST_2  \
                       --build-arg VITE_HK_HOST_3=$VITE_HK_HOST_3  \
                       -t registry.heroku.com/$HEROKU_APP_NAME/web .
          docker push registry.heroku.com/$HEROKU_APP_NAME/web

      # Release the Docker image on Heroku
      - name: Release the app
        run: |
          heroku container:release web --app $HEROKU_APP_NAME

    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
      VITE_PHD_CERTIFICATE_URL: ${{ secrets.VITE_PHD_CERTIFICATE_URL }}
      VITE_PHD_JURY_REPORT_URL: ${{ secrets.VITE_PHD_JURY_REPORT_URL }}
      VITE_ENG_CERTIFICATE_URL: ${{ secrets.VITE_ENG_CERTIFICATE_URL }}
      VITE_HK_HOST_1: ${{ secrets.VITE_HK_HOST_1 }}
      VITE_HK_HOST_2: ${{ secrets.VITE_HK_HOST_2  }}
      VITE_HK_HOST_3: ${{ secrets.VITE_HK_HOST_3 }}
      VITE_PORT: ${{ secrets.VITE_PORT }}